### ISSUE TITLE
[Enhancement] Add Changelog

### ISSUE THREAD

**Issue by fohfuu** [luk1337/SauceNAO#11]
Could you please add a changelog to the git, preferably in a way compatible with F-Droid? I like to know why an app is updating before I install. Thank you!

**Comment by luk1337** [comment]
I don't think I can do that for already released versions, but I can start doing that for next ones.

**Comment by luk1337** [comment]
Also, if you're curious to see what changed in last build, this is the changelog I put on Google Play:

```
* Added Turkish translations
* Enabled minification
* Updated databases list
```
