### ISSUE TITLE
cloudflare challenge 

### ISSUE THREAD

**Issue by JasonKhew96** [luk1337/SauceNAO#30]
apparently saucenao turned on cloudflare challenge recently, blocking app from searching image

EDIT: seems it's turned off for now

**Comment by luk1337** [comment]
Does this still happen? So far, I haven't managed to get a Cloudflare challenge since the day you reported it.

**Comment by JasonKhew96** [comment]
> Does this still happen? So far, I haven't managed to get a Cloudflare challenge since the day you reported it.

nope
