### ISSUE TITLE
Can't see media picker, only in SauceNAO

### ISSUE THREAD

**Issue by Starcr0ss** [luk1337/SauceNAO#99]
When I press "Select image", the image picker is supposed to appear but instead I just see a darkened screen. Taking a screenshot (thus I can't show this happening) or opening the multitasking menu shows that the media picker is visible and open, but reopening the app takes me back to that dim screen. The media picker works in every other app, so I am led to believe something is wrong with SauceNAO.
I am using Android 11.

**Comment by luk1337** [comment]
What kind of Android 11?

**Comment by Starcr0ss** [comment]
> What kind of Android 11?

Motorola, unrooted. It's on my Moto G Stylus (2021)

**Comment by luk1337** [comment]
> > What kind of Android 11?
> 
> Motorola, unrooted. It's on my Moto G Stylus (2021)

I tried running latest fdroid apk in firebase test lab on another Android 11 Motorola and it seems like media picker is showing up fine there?

![image](https://github.com/luk1337/SauceNAO/assets/6830979/df1fd1cc-c850-40a6-8a82-0b9c0d7e363d)

Are you able to check if git master works better for you? If so, running `./gradlew assembleDebug` will compile apk file at `./app/build/outputs/apk/github/debug/app-github-debug.apk`.

**Comment by luk1337** [comment]
can probably use https://github.com/luk1337/SauceNAO/commit/b52538ef4a8c2248d3878aa966b4fd91aeaafcc7 as a workaround here.
